-- Greek letters
local opts = { noremap = true, silent = true }
local buf_keymap = vim.api.nvim_buf_set_keymap

buf_keymap(0, 'i', '<C-g>a', '\\alpha', opts)
buf_keymap(0, 'i', '<C-g>A', 'A', opts)
buf_keymap(0, 'i', '<C-g>b', '\\beta', opts)
buf_keymap(0, 'i', '<C-g>B', 'B', opts)
buf_keymap(0, 'i', '<C-g>c', '\\chi', opts)
buf_keymap(0, 'i', '<C-g>C', 'X', opts)
buf_keymap(0, 'i', '<C-g>d', '\\delta', opts)
buf_keymap(0, 'i', '<C-g>D', '\\Delta', opts)
buf_keymap(0, 'i', '<C-g>e', '\\epsilon', opts)
buf_keymap(0, 'i', '<C-g>E', 'E', opts)
buf_keymap(0, 'i', '<C-g>1', '\\eta', opts)
buf_keymap(0, 'i', '<C-g>!', 'E', opts)
buf_keymap(0, 'i', '<C-g>g', '\\gamma', opts)
buf_keymap(0, 'i', '<C-g>G', '\\Gamma', opts)
buf_keymap(0, 'i', '<C-g>i', '\\iota', opts)
buf_keymap(0, 'i', '<C-g>I', 'I', opts)
buf_keymap(0, 'i', '<C-g>k', '\\kappa', opts)
buf_keymap(0, 'i', '<C-g>K', 'K', opts)
buf_keymap(0, 'i', '<C-g>l', '\\lambda', opts)
buf_keymap(0, 'i', '<C-g>L', '\\Lambda', opts)
buf_keymap(0, 'i', '<C-g>m', '\\mu', opts)
buf_keymap(0, 'i', '<C-g>M', 'M', opts)
buf_keymap(0, 'i', '<C-g>n', '\\nu', opts)
buf_keymap(0, 'i', '<C-g>N', 'N', opts)
buf_keymap(0, 'i', '<C-g>o', '\\omega', opts)
buf_keymap(0, 'i', '<C-g>O', '\\Omega', opts)
buf_keymap(0, 'i', '<C-g>f', '\\phi', opts)
buf_keymap(0, 'i', '<C-g>F', '\\Phi', opts)
buf_keymap(0, 'i', '<C-g>p', '\\psi', opts)
buf_keymap(0, 'i', '<C-g>P', '\\Psi', opts)
buf_keymap(0, 'i', '<C-g>3', '\\pi', opts)
buf_keymap(0, 'i', '<C-g>#', '\\Pi', opts)
buf_keymap(0, 'i', '<C-g>r', '\\rho', opts)
buf_keymap(0, 'i', '<C-g>R', 'R', opts)
buf_keymap(0, 'i', '<C-g>s', '\\sigma', opts)
buf_keymap(0, 'i', '<C-g>S', '\\Sigma', opts)
buf_keymap(0, 'i', '<C-g>t', '\\tau', opts)
buf_keymap(0, 'i', '<C-g>T', 'T', opts)
buf_keymap(0, 'i', '<C-g>2', '\\theta', opts)
buf_keymap(0, 'i', '<C-g>@', '\\Theta', opts)
buf_keymap(0, 'i', '<C-g>u', '\\upsilon', opts)
buf_keymap(0, 'i', '<C-g>U', '\\Upsilon', opts)
buf_keymap(0, 'i', '<C-g>x', '\\xi', opts)
buf_keymap(0, 'i', '<C-g>X', '\\Xi', opts)
buf_keymap(0, 'i', '<C-g>z', '\\zeta', opts)
buf_keymap(0, 'i', '<C-g>Z', 'Z', opts)

